= WSSCode Async Helpers
ifdef::env-github,env-cljdoc[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

`Core.async` is the standard way to handle async features in Clojure and ClojureScript programs.

Although core.async is built upon link:https://en.wikipedia.org/wiki/Communicating_sequential_processes[CSP],
often (specially in CLJS) we want to them more like link:https://en.wikipedia.org/wiki/Futures_and_promises[Promises/Futures].

Core.async provides a `promise-chan`, which is a channel that has a promise-like semantic:
after realization, any read on it will keep returning the same value. That's helpful but
this doesn't cover the problem of error propagation, in a promise system it's expected
that errors can flow up to be captured by some higher level code.

This library provide some helpers to deal with this problem, and also:

1. helpers to integrate with Javascript Promises in ClojureScript environments.
2. helpers to write tests using core.async and cljs.test.

== Including this library

This library uses separated namespaces for Clojure and ClojureScript, when using the
Clojure side, use the namespace `com.wsscode.async.async-clj`, and for ClojureScript
use `com.wsscode.async.async-cljs`. Unless pointed otherwise, the features on both
namespaces are the same.

If you want to use this with Clojure Common files, you can use the require like this:

[source,clojure]
----
(ns my-ns
  (:require [#?(:clj  com.wsscode.common.async-clj
                :cljs com.wsscode.common.async-cljs)
             :as wa
             :refer [go-promise <?]]))
----

== Error propagation

To deal with error propagation, the trick is to return the error object as the channel
value, but also throw that error when reading the channel. Let's illustrate that with
an example:

[source,clojure]
----
(ns my-ns
  (:require [com.wsscode.async.async-clj :refer [go-promise <?]))

(defn async-divide [x y]
  ; <1>
  (go-promise
    (/ x y)))

(defn run [d]
  (go-promise
    (try
      ; <2>
      (<? (async-divide 6 d))
      (catch Throwable _
        "ERROR"))))

(comment
  (<!! (run 2)) ; => 3 <3>
  (<!! (run 0)) ; => "ERROR" <4>
  )
----

<1> `go-promise` is similar to `go`, but will return a promise-channel, so in case this result gets
passed to multiple readers, all of them will get the realized value or error. This also
wraps the block in a try/catch, so if some exception happens it will get returned as the channel value.

<2> `<?` works like `<!`, but once it reads a value, it will check if it's an error, and
if so it will throw that error, propagating it up on the chain.

<3> propagate value back

<4> error propagated from async-divide trying to divide by zero

By following this pattern of error capture and send, this system ends up working in the
same ways you would expect a promise, all while still in the same `go` blocks, making
it compatible with standard core.async functionality. Later we will also talk about how
to integrate with Javascript Promises in this system.

=== Nil returns

Another difference when using `go-promise` is that different from regular `go`, you can
return `nil` as a value. Since the promise will always return the same value, a `nil`
is not ambiguous.

NOTE: In the implementation side, `go-promise` check if the value returned is `nil`, and
if so it just closes the channel, making it an effective `nil` value.

== Javascript Promises

While working in Javascript it's common to need to handle Promises, to help with this
there is a macro in this library that enables the read of JS promises as if they
were `core.async` channels, the `<!p` helper:

[source,clojure]
----
(ns my-ns
  (:require [com.wsscode.async.async-cljs :refer [go-promise <?]))

; <1>
(go-promise
  (-> (js/fetch "/") <!p
      (.text) <!p
      js/console.log))
----

<1> read the index text of the current domain, note we are waiting for two different
promises in this example, the first one for the fetch headers and the second to get the
body text.

== Javascript Async tests

Dealing with async tests in cljs.test can be annoying, the core doesn't have any integration
with core.async, neither it handles common problems like timing out a test. This library
provides a helper called `deftest-async` that aims to facilitate the tests of async core
using core.async. Example usage:

[source,clojure]
----
(ns com.wsscode.async.async-cljs-test
  (:require [clojure.test :refer [is are run-tests async testing deftest]]
            [com.wsscode.async.async-cljs :as wa :refer [deftest-async <! go]]))

(deftest-async my-test
  (is (= "foo" (<! (go "foo")))))
----

This macro will do a couple of things:

1. It will wrap the body in a `go-promise` block, allowing the use of parking operations
2. Try/catch this block, if any error happens (sync or async) that generates a test case that will fail with that error
3. Add a 2 seconds timeout, if the `go` block doesn't return in this time it will cancel and fail the test

You can configure the timeout duration, example:

[source,clojure]
----
(ns com.wsscode.async.async-cljs-test
  (:require [clojure.test :refer [is are run-tests async testing deftest]]
            [com.wsscode.async.async-cljs :as wa :refer [deftest-async <! go]]))

(deftest-async my-test
  {::wa/timeout 5000} ; 5 seconds timeout
  (is (= "foo" (<! (go "foo")))))
----

== API

Check the complete API at link:[cljdoc].
